"""
Common source schema definitions.

Provides a minimal SourceBase for all source schemas. Unlike
CanonicalBase, this does NOT include canonical provenance fields
(ingestion_run_id, ingested_at, record_hash, canonical id) because
those are generated by the ingestion pipeline, not supplied by
source systems.

Extra fields policy: "ignore" — source payloads may contain fields
not defined in the schema. Those fields are discarded from the
validated object but preserved in source_records.raw_payload for
audit/debugging. This avoids rejecting valid source records just
because the source added a field we don't map.
"""

from pydantic import BaseModel, ConfigDict


class SourceBase(BaseModel):
    """
    Minimal base for all source schemas.

    Configuration:
    - from_attributes=False: source data comes from dicts/JSON, not ORM
    - extra="ignore": unknown source fields are silently dropped from
      the validated object. The raw payload is separately preserved in
      source_records.raw_payload for audit. This prevents validation
      failures when a source adds a new field we haven't mapped yet.
    - No str_strip_whitespace: source values are preserved exactly.
      Whitespace handling belongs to D1 Normalization.
    """

    model_config = ConfigDict(
        extra="ignore",
    )
