"""B1: Layer 1 ORM schema — 7 canonical + 5 operational tables

Revision ID: 8bfd73b6af60
Revises: 0001
Create Date: 2026-09-07 14:01:20.119118
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bfd73b6af60'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False, comment='Unique logical name for this source, e.g. csv_demo'),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='Connector type: csv, odoo_mock, rest'),
    sa.Column('base_url', sa.String(length=1000), nullable=True, comment='Base URL for HTTP-based connectors'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Non-secret connector parameters (mappings, paths, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_configs')),
    sa.UniqueConstraint('source_name', name=op.f('uq_connector_configs_source_name'))
    )
    op.create_table('customers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('owner_source_id', sa.String(length=255), nullable=True, comment='Source-system ID of the account owner (employee)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='Creation timestamp from the source system'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False, comment='Logical source name, e.g. csv_demo, odoo_mock'),
    sa.Column('source_entity', sa.String(length=100), nullable=False, comment='Original entity/table/resource type in the source system'),
    sa.Column('source_id', sa.String(length=255), nullable=False, comment='Stable source-system identifier for this record'),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp from the source when available'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False, comment='When this version entered Layer 1'),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False, comment='Run that produced/updated this record'),
    sa.Column('record_hash', sa.String(length=64), nullable=False, comment='Deterministic hash of normalized business fields (excludes provenance)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('source_system', 'source_entity', 'source_id', name='uq_customers_source_identity')
    )
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    op.create_index('ix_customers_ingestion_run_id', 'customers', ['ingestion_run_id'], unique=False)
    op.create_index('ix_customers_source_updated_at', 'customers', ['source_updated_at'], unique=False)
    op.create_table('documents',
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True, comment='Full extracted document body for future RAG'),
    sa.Column('source_uri', sa.String(length=1000), nullable=True),
    sa.Column('owner_source_id', sa.String(length=255), nullable=True, comment='Source-system ID of the document owner'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='Document creation timestamp from the source system'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Document last-updated timestamp from the source system'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False, comment='Logical source name, e.g. csv_demo, odoo_mock'),
    sa.Column('source_entity', sa.String(length=100), nullable=False, comment='Original entity/table/resource type in the source system'),
    sa.Column('source_id', sa.String(length=255), nullable=False, comment='Stable source-system identifier for this record'),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp from the source when available'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False, comment='When this version entered Layer 1'),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False, comment='Run that produced/updated this record'),
    sa.Column('record_hash', sa.String(length=64), nullable=False, comment='Deterministic hash of normalized business fields (excludes provenance)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('source_system', 'source_entity', 'source_id', name='uq_documents_source_identity')
    )
    op.create_index('ix_documents_ingestion_run_id', 'documents', ['ingestion_run_id'], unique=False)
    op.create_index('ix_documents_source_updated_at', 'documents', ['source_updated_at'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('source_entity', sa.String(length=100), nullable=True, comment='Entity type being ingested; NULL if ingesting all entities'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='SUCCESS, PARTIAL_SUCCESS, FAILED, NOOP, RUNNING'),
    sa.Column('mode', sa.String(length=50), nullable=False, comment='full or incremental'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_unchanged', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('records_warnings', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True, comment='Human-readable summary of errors if any'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    op.create_index('ix_ingestion_runs_source_system', 'ingestion_runs', ['source_system'], unique=False)
    op.create_index('ix_ingestion_runs_started_at', 'ingestion_runs', ['started_at'], unique=False)
    op.create_index('ix_ingestion_runs_status', 'ingestion_runs', ['status'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False, comment='Logical source name, e.g. csv_demo, odoo_mock'),
    sa.Column('source_entity', sa.String(length=100), nullable=False, comment='Original entity/table/resource type in the source system'),
    sa.Column('source_id', sa.String(length=255), nullable=False, comment='Stable source-system identifier for this record'),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp from the source when available'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False, comment='When this version entered Layer 1'),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False, comment='Run that produced/updated this record'),
    sa.Column('record_hash', sa.String(length=64), nullable=False, comment='Deterministic hash of normalized business fields (excludes provenance)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('source_system', 'source_entity', 'source_id', name='uq_organizations_source_identity')
    )
    op.create_index('ix_organizations_ingestion_run_id', 'organizations', ['ingestion_run_id'], unique=False)
    op.create_index('ix_organizations_source_updated_at', 'organizations', ['source_updated_at'], unique=False)
    op.create_table('deals',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='Deal value in fixed-precision decimal (never float)'),
    sa.Column('currency', sa.String(length=10), nullable=True, comment='ISO currency code, e.g. USD, INR'),
    sa.Column('probability', sa.Numeric(precision=5, scale=2), nullable=True, comment='Win probability as percentage (0.00-100.00)'),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('customer_source_id', sa.String(length=255), nullable=True, comment='Original source customer key; preserved for unresolved FK tracking'),
    sa.Column('owner_source_id', sa.String(length=255), nullable=True, comment='Source-system ID of the deal owner (employee)'),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False, comment='Logical source name, e.g. csv_demo, odoo_mock'),
    sa.Column('source_entity', sa.String(length=100), nullable=False, comment='Original entity/table/resource type in the source system'),
    sa.Column('source_id', sa.String(length=255), nullable=False, comment='Stable source-system identifier for this record'),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp from the source when available'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False, comment='When this version entered Layer 1'),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False, comment='Run that produced/updated this record'),
    sa.Column('record_hash', sa.String(length=64), nullable=False, comment='Deterministic hash of normalized business fields (excludes provenance)'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_deals_customer_id_customers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals')),
    sa.UniqueConstraint('source_system', 'source_entity', 'source_id', name='uq_deals_source_identity')
    )
    op.create_index('ix_deals_customer_id', 'deals', ['customer_id'], unique=False)
    op.create_index('ix_deals_ingestion_run_id', 'deals', ['ingestion_run_id'], unique=False)
    op.create_index('ix_deals_source_updated_at', 'deals', ['source_updated_at'], unique=False)
    op.create_table('employees',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('manager_source_id', sa.String(length=255), nullable=True, comment='Source-system ID of the manager; may not resolve to a canonical employee'),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False, comment='Logical source name, e.g. csv_demo, odoo_mock'),
    sa.Column('source_entity', sa.String(length=100), nullable=False, comment='Original entity/table/resource type in the source system'),
    sa.Column('source_id', sa.String(length=255), nullable=False, comment='Stable source-system identifier for this record'),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp from the source when available'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False, comment='When this version entered Layer 1'),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False, comment='Run that produced/updated this record'),
    sa.Column('record_hash', sa.String(length=64), nullable=False, comment='Deterministic hash of normalized business fields (excludes provenance)'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employees_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('source_system', 'source_entity', 'source_id', name='uq_employees_source_identity')
    )
    op.create_index('ix_employees_email', 'employees', ['email'], unique=False)
    op.create_index('ix_employees_ingestion_run_id', 'employees', ['ingestion_run_id'], unique=False)
    op.create_index('ix_employees_organization_id', 'employees', ['organization_id'], unique=False)
    op.create_index('ix_employees_source_updated_at', 'employees', ['source_updated_at'], unique=False)
    op.create_table('ingestion_cursors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('source_entity', sa.String(length=100), nullable=False),
    sa.Column('last_cursor', sa.String(length=500), nullable=True, comment='Opaque watermark: timestamp, offset, page token, etc.'),
    sa.Column('last_successful_run_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_successful_run_id'], ['ingestion_runs.id'], name=op.f('fk_ingestion_cursors_last_successful_run_id_ingestion_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_cursors')),
    sa.UniqueConstraint('source_system', 'source_entity', name='uq_ingestion_cursors_source_key')
    )
    op.create_table('ingestion_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('source_entity', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True, comment='Source record identifier, if known'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='ERROR, WARNING, or INFO'),
    sa.Column('error_code', sa.String(length=100), nullable=True, comment='Machine-readable error classification'),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True, comment='Extended detail, raw record excerpt, or stack trace'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], name=op.f('fk_ingestion_errors_ingestion_run_id_ingestion_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_errors'))
    )
    op.create_index('ix_ingestion_errors_ingestion_run_id', 'ingestion_errors', ['ingestion_run_id'], unique=False)
    op.create_index('ix_ingestion_errors_severity', 'ingestion_errors', ['severity'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=15, scale=2), nullable=True, comment='Project budget in fixed-precision decimal'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('customer_source_id', sa.String(length=255), nullable=True, comment='Source-system customer key for this project'),
    sa.Column('owner_source_id', sa.String(length=255), nullable=True, comment='Source-system ID of the project owner (employee)'),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False, comment='Logical source name, e.g. csv_demo, odoo_mock'),
    sa.Column('source_entity', sa.String(length=100), nullable=False, comment='Original entity/table/resource type in the source system'),
    sa.Column('source_id', sa.String(length=255), nullable=False, comment='Stable source-system identifier for this record'),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp from the source when available'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False, comment='When this version entered Layer 1'),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False, comment='Run that produced/updated this record'),
    sa.Column('record_hash', sa.String(length=64), nullable=False, comment='Deterministic hash of normalized business fields (excludes provenance)'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_projects_customer_id_customers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('source_system', 'source_entity', 'source_id', name='uq_projects_source_identity')
    )
    op.create_index('ix_projects_customer_id', 'projects', ['customer_id'], unique=False)
    op.create_index('ix_projects_ingestion_run_id', 'projects', ['ingestion_run_id'], unique=False)
    op.create_index('ix_projects_source_updated_at', 'projects', ['source_updated_at'], unique=False)
    op.create_table('source_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('source_entity', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Original source payload preserved for audit and debugging'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='Hash of the raw payload for change detection'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], name=op.f('fk_source_records_ingestion_run_id_ingestion_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_records'))
    )
    op.create_index('ix_source_records_ingestion_run_id', 'source_records', ['ingestion_run_id'], unique=False)
    op.create_index('ix_source_records_source_identity', 'source_records', ['source_system', 'source_entity', 'source_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='Ticket creation timestamp from the source system'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_source_id', sa.String(length=255), nullable=True, comment='Source-system customer key for this ticket'),
    sa.Column('assignee_source_id', sa.String(length=255), nullable=True, comment='Source-system ID of the assigned employee'),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False, comment='Logical source name, e.g. csv_demo, odoo_mock'),
    sa.Column('source_entity', sa.String(length=100), nullable=False, comment='Original entity/table/resource type in the source system'),
    sa.Column('source_id', sa.String(length=255), nullable=False, comment='Stable source-system identifier for this record'),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp from the source when available'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False, comment='When this version entered Layer 1'),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False, comment='Run that produced/updated this record'),
    sa.Column('record_hash', sa.String(length=64), nullable=False, comment='Deterministic hash of normalized business fields (excludes provenance)'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_support_tickets_customer_id_customers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_tickets')),
    sa.UniqueConstraint('source_system', 'source_entity', 'source_id', name='uq_support_tickets_source_identity')
    )
    op.create_index('ix_support_tickets_created_at', 'support_tickets', ['created_at'], unique=False)
    op.create_index('ix_support_tickets_customer_id', 'support_tickets', ['customer_id'], unique=False)
    op.create_index('ix_support_tickets_ingestion_run_id', 'support_tickets', ['ingestion_run_id'], unique=False)
    op.create_index('ix_support_tickets_source_updated_at', 'support_tickets', ['source_updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_support_tickets_source_updated_at', table_name='support_tickets')
    op.drop_index('ix_support_tickets_ingestion_run_id', table_name='support_tickets')
    op.drop_index('ix_support_tickets_customer_id', table_name='support_tickets')
    op.drop_index('ix_support_tickets_created_at', table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index('ix_source_records_source_identity', table_name='source_records')
    op.drop_index('ix_source_records_ingestion_run_id', table_name='source_records')
    op.drop_table('source_records')
    op.drop_index('ix_projects_source_updated_at', table_name='projects')
    op.drop_index('ix_projects_ingestion_run_id', table_name='projects')
    op.drop_index('ix_projects_customer_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_ingestion_errors_severity', table_name='ingestion_errors')
    op.drop_index('ix_ingestion_errors_ingestion_run_id', table_name='ingestion_errors')
    op.drop_table('ingestion_errors')
    op.drop_table('ingestion_cursors')
    op.drop_index('ix_employees_source_updated_at', table_name='employees')
    op.drop_index('ix_employees_organization_id', table_name='employees')
    op.drop_index('ix_employees_ingestion_run_id', table_name='employees')
    op.drop_index('ix_employees_email', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_deals_source_updated_at', table_name='deals')
    op.drop_index('ix_deals_ingestion_run_id', table_name='deals')
    op.drop_index('ix_deals_customer_id', table_name='deals')
    op.drop_table('deals')
    op.drop_index('ix_organizations_source_updated_at', table_name='organizations')
    op.drop_index('ix_organizations_ingestion_run_id', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_ingestion_runs_status', table_name='ingestion_runs')
    op.drop_index('ix_ingestion_runs_started_at', table_name='ingestion_runs')
    op.drop_index('ix_ingestion_runs_source_system', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index('ix_documents_source_updated_at', table_name='documents')
    op.drop_index('ix_documents_ingestion_run_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_customers_source_updated_at', table_name='customers')
    op.drop_index('ix_customers_ingestion_run_id', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_table('customers')
    op.drop_table('connector_configs')
    # ### end Alembic commands ###
