"""
Database engine and metadata for Layer 1.

Provides the SQLAlchemy engine, DeclarativeBase, and session factory.
This module is the single source of truth for database connectivity,
used by both the application runtime and Alembic migrations.

ORM models (B1) will import Base from here and define tables.
Alembic's env.py imports target_metadata from here.

The project uses synchronous SQLAlchemy throughout.
"""

from sqlalchemy import MetaData, create_engine
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from app.core.config import get_settings

# Naming convention for constraints. Makes autogenerated migration names
# deterministic and allows Alembic to correctly detect renames/drops.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """
    Declarative base for all Layer 1 ORM models.

    Models will be defined in app/persistence/models/ during B1.
    This base class exists here so that both the application and
    Alembic can share the same metadata object.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def get_engine():
    """Create and return a synchronous SQLAlchemy engine.

    G2: SQL is never echoed and bound parameters are hidden from database
    error messages, in every environment, so source payload values cannot
    reach logs (spec Section 14).
    """
    settings = get_settings()
    return create_engine(
        settings.effective_database_url,
        echo=False,
        hide_parameters=True,
        pool_pre_ping=True,
    )


def get_session_factory():
    """Create and return a session factory bound to the engine."""
    engine = get_engine()
    return sessionmaker(bind=engine, class_=Session, expire_on_commit=False)
